### ISSUE TITLE
About pretrain weights

### ISSUE THREAD

**Issue by LogSSim** [NVlabs/M2T2#6]
Thanks for your contributions on robotics. So where could I get the pertrained model（m2t2_language.pth）file? 
I applied, but nobody replied.

**Comment by wentaoyuan** [comment]
Here is the updated link for the pretrained weights: https://huggingface.co/wentao-yuan/m2t2.

**Comment by adithyamurali** [comment]
README has also been updated with the correct updated link. @LogSSim let us know if have other issues, closing this
